### ISSUE TITLE
Ledger Hardware Wallet Web implementation of the communication layer, using U2F api - DEPRECATED

### ISSUE THREAD

**Issue by BearCooder** [ecadlabs/taquito-react-template#12]
Not sure if that package should be updated with a new package but I noticed that it says that the package is **deprecated**: `"@ledgerhq/hw-transport-u2f"`
Also the github repo is archived and has a note that its deprecated: https://github.com/LedgerHQ/ledgerjs

_This repository is now deprecated. We moved to a new mono repository architecture containing all of Ledger Live JavaScript Ecosystem that you can find [here](https://github.com/ledgerhq/ledger-live). You can follow the [migration guide](https://github.com/LedgerHQ/ledger-live/wiki/Migrate-from-previous-repositories#migration) to help you make the transition._

**Comment by claudebarde** [comment]
The package has been removed from the dapp altogether, the purpose of the dapp is to give a simple example of Taquito/Beacon with React and connecting a cold wallet is a more advanced endeavour.
