### ISSUE TITLE
"Disconnect wallet" button needs to click twice

### ISSUE THREAD

**Issue by camlspotter** [ecadlabs/taquito-react-template#14]
The first click on "Disconnect wallet" button does not work.  It must be clicked twice somehow.

How to reproduce:

- Click "Connect with wallet" and choose a wallet (I use Temple)
- At "Make a transfer" pane, click "Disconnect wallet".  It does not disconnect the wallet.  The screen stays same.
- Disconnection requires the second click on "Disconnect wallet".
- Reconnection fails somehow.  "Connect with wallet" shows the Beacon wallet selector window but nothing happens if I choose a wallet.  The screen keeps displaying the QR code.
- Reloading the page fixes the issue.

I use the latest master (commit 18dc48d84641d11e358d8f0836943f53915bc7c2) with Chrome on Mac OS.

**Comment by camlspotter** [comment]
```
npm list
./taquito-react-template
├── @ledgerhq/hw-transport-u2f@5.22.0
├── @taquito/beacon-wallet@14.0.0
├── @taquito/ledger-signer@14.0.0
├── @taquito/taquito@14.0.0
├── @testing-library/jest-dom@5.16.5
├── @testing-library/react@13.4.0
├── @testing-library/user-event@14.4.3
├── @types/jest@29.2.0
├── @types/ledgerhq__hw-transport-u2f@4.21.2
├── @types/node@18.11.7
├── @types/react-dom@18.0.7
├── @types/react@18.0.23
├── buffer@6.0.3
├── os-browserify@0.3.0
├── qrcode-generator@1.4.4
├── react-app-rewired@2.2.1
├── react-dom@18.2.0
├── react-scripts@5.0.1
├── react@18.2.0
├── stream-browserify@3.0.0
└── typescript@4.8.4
```

**Comment by claudebarde** [comment]
For some reason, the `removeAllPeers` method on the DappClient instance was making the function responsible for resetting the state of the dapp fail on the first try, but not on the second 😜
I used the `clearActiveAccount` method instead and it was working properly. Please clone the latest version of the repo and let me know if the issue you faced is gone.

**Comment by camlspotter** [comment]
Thanks!  Now disconnection and reconnection both work with any glitch!
