### ISSUE TITLE
Update to v8

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito-react-template#3]
Update the taquito-react-template project to use v8 taquito, and update it to use `edonet` by default.

**Comment by claudebarde** [comment]
I can work on this, it requires updates of the BeaconWallet I am familiar with. There is also an error caused by Beacon I informed the AirGap team about already.

**Comment by claudebarde** [comment]
@jevonearth Using `edonet` by default will prevent users from using the Kukai wallet to connect to the dapp (using edonet instead of delphinet triggers a `Network Error` from Beacon when trying to connect with Kukai). I updated it but it's still working on delphinet, what's your opinion about that?

**Comment by claudebarde** [comment]
This was done and the dapp is already using v9.
