### ISSUE TITLE
Display NFT's after wallet connection

### ISSUE THREAD

**Issue by paulo60pg** [ecadlabs/taquito-react-template#4]
Is there a way to display NFT's easily after the wallet connection ?

**Comment by claudebarde** [comment]
The goal of the React template is to be a simple boilerplate to quickly start building any kind of dapp using React.
If you want to display NFTs, you can use Taquito to fetch the data of the contract where the NFTs are stored and use them to display the NFTs :)

**Comment by claudebarde** [comment]
I am closing the issue as the display of owned NFTs goes beyond the scope of this template and is therefore not an issue per se.
