### ISSUE TITLE
Bug : Status "loading, please wait" after closing Beacon Wallet

### ISSUE THREAD

**Issue by paulo60pg** [ecadlabs/taquito-react-template#5]
If you click connect wallet, Beacon opens. If you close the Beacon pop up, the button are disabled and "loading, please wait" is displayed. You can't click to connect. You can't stop the loading either.
The only way is to refresh the page, to have the connect buttons accessible again.

![image](https://user-images.githubusercontent.com/44470174/112621960-a69cda00-8e2a-11eb-8bbb-f85485f4288e.png)

**Comment by claudebarde** [comment]
Hey!
This was fixed in the [latest commit](https://github.com/ecadlabs/taquito-react-template/commit/cdacaedd097654b31325c079e2a1645543ce7d33), thank you for reporting it!
